version: "4"

services:
  app:
    container_name: api
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    volumes:
      - ./logs:/logs
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - api_network

  postgres:
    container_name: api_postgres
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - docker.env
    networks:
      - api_network

  redis:
    container_name: api_redis
    image: redis:latest
    restart: always
    networks:
      - api_network

networks:
  api_network:
    driver: bridge