basePath: /
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  internal_api_v1.commentCreateInput:
    properties:
      comment:
        type: string
      post_id:
        type: string
    type: object
  internal_api_v1.commentDeleteInput:
    properties:
      comment_id:
        type: string
    type: object
  internal_api_v1.commentUpdateInput:
    properties:
      comment_id:
        type: string
      new_comment:
        type: string
    type: object
  internal_api_v1.postCreateInput:
    properties:
      text:
        type: string
      title:
        type: string
    type: object
  internal_api_v1.reactionCreateInput:
    properties:
      post_id:
        type: string
      reaction:
        type: string
    required:
    - post_id
    - reaction
    type: object
  internal_api_v1.reactionDeleteInput:
    properties:
      reaction_id:
        type: string
    required:
    - reaction_id
    type: object
  internal_api_v1.signInInput:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  internal_api_v1.signUpInput:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
  internal_api_v1.updateUsernameInput:
    properties:
      new_username:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  internal_api_v1.userUpdateFullNameInput:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Api for social networking. Include posts, reactions and comments
  title: Api for social network
  version: "1.0"
paths:
  /api/v1/posts/comment:
    get:
      consumes:
      - application/json
      description: Get comment for post by commentId
      parameters:
      - description: comment id
        in: query
        name: comment_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get comment
      tags:
      - comment
  /api/v1/posts/comment/create:
    post:
      consumes:
      - application/json
      description: Create comment for post
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.commentCreateInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Create comment
      tags:
      - comment
  /api/v1/posts/comment/delete:
    delete:
      consumes:
      - application/json
      description: Delete comment for post
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.commentDeleteInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Delete comment
      tags:
      - comment
  /api/v1/posts/comment/update:
    put:
      consumes:
      - application/json
      description: Update comment for post by commentId
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.commentUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Update comment
      tags:
      - comment
  /api/v1/posts/post:
    get:
      consumes:
      - application/json
      description: Get post by id
      parameters:
      - description: post id
        in: query
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get post
      tags:
      - post
  /api/v1/posts/post/comments:
    get:
      consumes:
      - application/json
      description: Get all post comments by post id
      parameters:
      - description: post id
        in: query
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get post comments
      tags:
      - post
  /api/v1/posts/post/create:
    post:
      consumes:
      - application/json
      description: Create post
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.postCreateInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Create post
      tags:
      - post
  /api/v1/posts/reaction:
    get:
      consumes:
      - application/json
      description: Get reaction for post by id
      parameters:
      - description: reaction id
        in: query
        name: reaction_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get reaction
      tags:
      - reaction
  /api/v1/posts/reaction/create:
    post:
      consumes:
      - application/json
      description: Create reaction for post
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.reactionCreateInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Create reaction
      tags:
      - reaction
  /api/v1/posts/reaction/delete:
    delete:
      consumes:
      - application/json
      description: Delete reaction for post by id
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.reactionDeleteInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Delete reaction
      tags:
      - reaction
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get user by username
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get user
      tags:
      - user
  /api/v1/user/comments:
    get:
      consumes:
      - application/json
      description: Get all user comments
      parameters:
      - description: username
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Get user comments
      tags:
      - user
  /api/v1/user/update/full-name:
    put:
      consumes:
      - application/json
      description: Update user full name
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.userUpdateFullNameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      security:
      - JWT: []
      summary: Update user full name
      tags:
      - user
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Sign in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign up
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.signUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Sign up
      tags:
      - auth
  /auth/user/delete:
    delete:
      consumes:
      - application/json
      description: Delete  user
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Delete user
      tags:
      - auth
  /user/update/username:
    put:
      consumes:
      - application/json
      description: Update user username
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_api_v1.updateUsernameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Update username
      tags:
      - auth
securityDefinitions:
  JWT:
    description: JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
